name: Build Macro EXE

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pyinstaller pywin32 pyautogui pynput keyboard

    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed background_macro.py

    - name: Upload Finished EXE
      uses: actions/upload-artifact@v4
      with:
        name: Macro-Executable
        path: dist/*.exe
